# Generated by Django 4.2.5 on 2023-09-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_monthly_order_storage_orderitem_monthlyitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthly',
            name='garden',
        ),
    ]
