# Generated by Django 4.2.5 on 2023-09-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_remove_monthly_garden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly',
            name='month',
            field=models.CharField(choices=[(1, 'Yanvar'), (2, 'Fevral'), (3, 'Mart'), (4, 'Aprel'), (5, 'May'), (6, 'Iyun'), (7, 'Iyul'), (8, 'Avgust'), (9, 'Sentyabr'), (10, 'Oktyabr'), (11, 'Noyabr'), (12, 'Dekabr')], max_length=10),
        ),
    ]
