# Generated by Django 4.2.5 on 2023-09-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_remove_monthlyitem_quantity_monthly_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.garden')),
                ('monthly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.monthly')),
            ],
        ),
        migrations.CreateModel(
            name='LimitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_quantity', models.FloatField(default=0)),
                ('remaining_quantity', models.FloatField(default=0)),
                ('price', models.IntegerField()),
                ('market_price', models.IntegerField()),
                ('limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.limit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.product')),
            ],
        ),
        migrations.DeleteModel(
            name='MonthlyItem',
        ),
    ]
