# Generated by Django 4.2.5 on 2023-09-22 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0007_order_monthly'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='monthly',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='garden.monthly'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sell',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
