# Generated by Django 4.2.5 on 2023-09-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0008_sell_monthly_alter_sell_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseitem',
            name='monthly',
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='expense',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='garden.expense'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
