# Generated by Django 4.2.5 on 2023-09-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0009_remove_expenseitem_monthly_expenseitem_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limititem',
            name='market_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='limititem',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storage',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Qoldiq'),
        ),
    ]
