# Generated by Django 4.2 on 2023-09-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0010_alter_limititem_market_price_alter_limititem_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garden',
            options={'verbose_name': "'Bog'cha", 'verbose_name_plural': "Bog'chalar"},
        ),
    ]
