# Generated by Django 4.2.5 on 2023-09-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0011_alter_garden_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Xarajat', 'verbose_name_plural': 'Xarajatlar'},
        ),
        migrations.AlterModelOptions(
            name='garden',
            options={'verbose_name': "Bog'cha", 'verbose_name_plural': "Bog'chalar"},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'Ombor', 'verbose_name_plural': 'Ombor'},
        ),
        migrations.AddField(
            model_name='garden',
            name='tg_user_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
