# Generated by Django 4.2.5 on 2023-09-29 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0012_alter_expense_options_alter_garden_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='limit',
            options={'verbose_name': 'Limit', 'verbose_name_plural': 'Limit'},
        ),
        migrations.AlterModelOptions(
            name='monthly',
            options={'verbose_name': 'Oy', 'verbose_name_plural': 'Oylar'},
        ),
        migrations.AlterModelOptions(
            name='sell',
            options={'verbose_name': 'Yetkazib berish', 'verbose_name_plural': 'Yetkazib berish'},
        ),
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='excel files', verbose_name='Excel file')),
                ('monthly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.monthly')),
            ],
            options={
                'verbose_name': 'Excel filelar',
                'verbose_name_plural': 'Excel filelar',
            },
        ),
    ]
