# Generated by Django 4.2.5 on 2023-10-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0014_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='adress',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='stir',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
