# Generated by Django 4.2.5 on 2023-10-07 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0015_garden_adress_garden_stir'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excelfile',
            options={'verbose_name': 'Excel fayllar', 'verbose_name_plural': 'Excel fayllar'},
        ),
    ]
