# Generated by Django 4.2.5 on 2023-10-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0017_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='factura'),
        ),
    ]
